//   Register = 
// REGISTER_START
// REGISTER_SUCCESS
// REGISTER_FAILURE

// 	login = 
// LOGIN_START
// LOGIN_SUCCESS
// LOGIN_FAILURE

// 	fetchingItems = 
// FETCH_ITEMS_START
// FETCH_ITEMS_SUCCESS
// FETCH_ITEMS_FAILURE

// 	addItem = 
// ADD_ITEM
// ADD_ITEM_SUCCESS
// ADD_ITEM_FAILURE

// 	updateItem = 
// UPDATE_ITEM
// UPDATE_ITEM_SUCCESS
// UPDATE_ITEM_FAILURE

// 	deleteItem = 
// DELETE_ITEM
// DELETE_ITEM_SUCCESS
// DELETE_ITEM_FAILURE

// 	sortItem = 
// SORTING_ITEM
// SORTIING_ITEM_SUCCESS
// SORTING_ITEM_FAILURE

// 	stockAlert = 
// ITEM_STOCK_ALERT
// ITEM_STOCK_ALERT_SUCCESS
// ITEM_STOCK_ALERT_FAILURE
